blank_issues_enabled: true
contact_links:
  - name: Xpublish-community show and tell
    url: https://github.com/xpublish-community/community/discussions/categories/show-and-tell
    about: Please show off and discuss experimental projects here.
